### ISSUE TITLE
UTF-8 

### ISSUE THREAD

**Issue by amihanya** [tuarua/DesktopToastANE#1]
Hi,
Great job! it work well.
When i try to send a toast at Hebrew. i get Gibberish.
i try to make the XML on UTF-8 encoding but its style Gibberish.

**Comment by tuarua** [comment]
Is this on Windows ?

**Comment by amihanya** [comment]
yes.

**Comment by tuarua** [comment]
try the latest version I have committed. I added UTF-8 encoding to the string conversion in the Win code

**Comment by amihanya** [comment]
the last ane have a problem, Error: Cannot find cantral directory

**Comment by tuarua** [comment]
I need more detail. A screenshot, a full log.
I don't reference any "cantral" directory in my code

**Comment by amihanya** [comment]
<img src="https://i2.wp.com/amihanya.files.wordpress.com/2017/02/cantral.png?ssl=1&w=450">

**Comment by tuarua** [comment]
Try downloading again. Looks like the file was corrupted.

**Comment by amihanya** [comment]
i try, but i style get this Error (flash develop).

**Comment by tuarua** [comment]
Download the file directly: [](https://github.com/tuarua/DesktopToastANE/blob/master/native_extension/ane/DesktopToastANE.ane)

I don't use Flash Develop so can't help with that. I use both IntelliJ and Flash Builder and everything is fine

**Comment by amihanya** [comment]
ok, i clear cash, and download.
and now its work! the file is ok.
and the hebrew work great!
תודה רבה 👍

**Comment by amihanya** [comment]
if you want i can send you the project on FlashDevelop.

**Comment by tuarua** [comment]
Ok, that's good - Glad it displays your text correctly.
