### ISSUE TITLE
isSupported

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#10]
Suggestion: Add a isSupported in both macOS and Windows that returns true if the operation system is supported including the minimum OS version.

**Comment by tuarua** [comment]
see changeling

**Comment by hferreira** [comment]
Thanks.

Currently I'm in the middle of the process of change an App that use shared runtime to captiva runtime (it's a requirements to ANE's) then I will give another try to your ANE.

Regards,
Hugo.
