### ISSUE TITLE
Remove the C++ distributable dependency

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#14]
May this remove the need for Visual C++ Distributable on the client machine with the price of increasing a little the application size ?
https://www.codeproject.com/Tips/851725/Visual-Cplusplus-How-to-Create-Standalone-Win-Appl

I could do a new test on a clean Windows 10 installation.

**Comment by tuarua** [comment]
Hi,
I have seen that article before. I'm aware of it.

Method 1 is impossible as ANE dlls must be created as multi-threaded dynamic.
Method 2 I tried but it didn't make any difference. 

Regardless of possibility there are 2 big reasons why this is not a good approach:
1) If there are MS security updates to VC++ Dist then I am then responsible for patching every release
2) Using a different ANE which uses the shared VC++ Dist will cause symbol clashes.

You may say you don't care about # 1 and you only intend to use this 1 ANE but there are many people using this ANE. I have to consider all users.

Please accept that this ANE requires 1 standard MS dependency. It is the standard approach to building Win apps in 2017 and with ANEs your apps are moving into that domain.
Look at the sample installer provided with WebViewANE. It handles this dependency and will produce a solid and professional looking app experience.

I have to mark this as won't fix.

**Comment by hferreira** [comment]
Thank you for the detailed explanation.
For me point 2 is more than a reason to do that.
Of course that you already thought about this but I have one last question.

I read somewhere (perhaps I should test) but if you deploy the executable with the dependencies dll's on the same folder, we don't need to install C++ distributable.
Do you know any thing about that ?

**Comment by tuarua** [comment]
Yes you can do this.
Copy the dll from C:\Windows\SysWOW64\msvcp140.dll (assuming you have this installed)
It's weird but sysWOW64 is where 32bit dlls live. 64bit live in system32. Confusing eh.

**Comment by tuarua** [comment]
Hmm, you might also need some others.
See this page.
https://msdn.microsoft.com/en-us/library/8kche8ah.aspx

**Comment by hferreira** [comment]
OK, you confirm my suspicious.
I will do the test in a clean Windows 10 installation on a virtual machine.
The final goal is to deploy a simple installation with zero dependencies.
I will do the test and confirm all the dependencies for any one that find this thread and have the same requirements.

**Comment by tuarua** [comment]
Cool

**Comment by hferreira** [comment]
All google search was dead end so I put my hands on work and found the minimum requirements as possible to put this ANE working on a clean Windows 10 with 0 updates.
No registry, no setup, no dll hell, just copy and past.
At the end, all we need is two simple dll's that you can grab directly from C:\Windows\SysWOW64
This 2 dlls should be on the same directory of the exe AIR app:
msvcp140.dll - 430 KB
vcruntime140.dll - 82 KB

**Comment by tuarua** [comment]
Ok. That's good to know it's just these 2.

**Comment by hferreira** [comment]
Yes, indeed. I was surprised my self too but it's true. This only 2 dll's are the minimum required to work with your ANE on a Windows 10 clean environment !
