### ISSUE TITLE
Does this module handle Push Notifications to Mac & Windows ?

### ISSUE THREAD

**Issue by yozef** [tuarua/DesktopToastANE#2]
For Adobe AIR to handle these Push Notifications?

If so is there any steps to set up listening for Push Notifications?

**Comment by tuarua** [comment]
No

**Comment by yozef** [comment]
Therefore, I assume push notifications for desktop apps are not yet supported in AIR.

**Comment by tuarua** [comment]
I have only ever heard of push notifications in UWP apps for Windows 10. AIR runs as a Win32 exe so it's unlikely it'll ever occur.

**Comment by tuarua** [comment]
However you could use something like monaserver to push a notification to your app via rtmfp
http://www.monaserver.ovh/
