### ISSUE TITLE
Windows activation suggestion

### ISSUE THREAD

**Issue by rodrigogermanlopez** [tuarua/DesktopToastANE#3]
Not an issue, just a suggestion.
Maybe you could add this code on the samples classes, inside **onToastClicked** before **NativeA pplication.nativeApplication.activate();** just to make sure the window (app) is restored properly:

```
		var window:NativeWindow = stage.starling.nativeStage.nativeWindow ;
		if( window.displayState == NativeWindowDisplayState.MINIMIZED ){
			window.restore();
		}
		if( !window.visible ) {
			window.visible = true ;
		}
```

**Comment by tuarua** [comment]
Thanks for the suggestion Code now included
