### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#4]
I tried: dtANE.init(NativeApplication.nativeApplication.applicationID,"Toast ANE Sample");
But init funcion does not exist.

**Comment by tuarua** [comment]
What OS?
Are you using the provided example ?

Can you give the full error output

**Comment by hferreira** [comment]
IntelliJ + Flex + macOS
This init function is not available

**Comment by tuarua** [comment]
That's not a full error output. I need a screen grab or the full console output.
Are you using the provided example ?

If you are targeting macOS you need to use the sample code in StarlingRoot_OSX.as
Important lines are
37: use namespace osx;

45:dtANE.init();

**Comment by hferreira** [comment]
use namespace osx did the trick !
Thank you.

- But I want also support Windows 10, so I need to have 2 class, one for macOS toasts and another one for Windows 10 toasts and the begin of the application validate if is macOS or Windows ?
- If I run the macOS code on Windows I will thru an exception or the code will simple be ignored ?
- If I run the Windows toast code on non supported OS like XP, it will thru an exception or the code will simple be ignored ?

**Comment by tuarua** [comment]
1. Yes, use different classes for each Win8, 10, OSX. Check which OS the user is using. The Toasts are so different on each platform I couldn't write a single API.
2. It will throw an exception
3. The app will crash. Only call the ANE functions on Win 8, 10 and OSX

**Comment by hferreira** [comment]
Thank you very much for your great ANE.

My needs is for macOS and Windows 10 and I support Windows XP >= so I will write a class for macOS using your ANE with specific code and another one for Windows 10 using your ANE using specific code and one main class for Toast that receive a message.
If if macOS, will call the macOS class, if is Windows 10 will call Windows 10 class otherwise, will ignore the message.

My toast will be very, very generic and will be a message to the user without buttons.

Thank you,
Hugo.

**Comment by tuarua** [comment]
No problems. Sounds like a good way to do it.
Yes, I added ALL the features on each platform, but most users will only want a message and image.
