### ISSUE TITLE
Windows 10 requirements

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#5]
Does your Toast ANE have any requirements on Windows 10 as your WebViewANE with C++ dependencies ?

**Comment by tuarua** [comment]
It needs Microsoft Visual C++ 2015 Redistributable (x86) runtime installed.

**Comment by hferreira** [comment]
I only want to support Windows 10 + macOS, so I will try to run on a clean Windows 10 on a virtual machine to see how it works.
Perhaps Windows 10 may already include the necessary files.

**Comment by tuarua** [comment]
Windows 10 should have the 2015 C++ redistributable (and earlier) as default. It will be listed under Programs and Features. Please let me know if the clean VM has this installed. Thanks.

**Comment by hferreira** [comment]
I will do a test on a clean Windows 10 and let you know the results.
I'm now without time but probably I can do this latter next week.

**Comment by hferreira** [comment]
I will do the test this week.
I'm installing now a clean Windows 10 on a virtual machine.

**Comment by hferreira** [comment]
It's confirmed.
With a clean install of Windows 10 Pro without Internet connection (so there is no updates), one sample AIR App with your ANE does not work (don't crash but also don't show the toast).
After install the Visual C++ 2015 distributable (x86), the ANE works.

**Comment by tuarua** [comment]
ok, I will update the README to reflect that this is needed

**Comment by hferreira** [comment]
It's a pity because I would love to use this ANE.
Perhaps I will use for macOS and in case of Windows 10 I add a button "Enable local notification on this machine" and then call Visual C++ 2015 distributable (x86) directly from the offical web site.

2 suggestions:
1. The isSupported method on macOS only returns true in case of the macOS have the minimum OS version required;
2. Add a new method on Windows side of the ANE (for example haveRuntimeRequirements) that check if Visual C++ 2015 distributable is installed on the local machine (perhaps check for a vital DLL from the runtime).

**Comment by tuarua** [comment]
Erm, any program, or dll written with Visual Studio needs these runtime dlls. This ANE is not a rarity or special. 
Windows programs should be packaged with an installer such as Inno setup or Wix. These installers are configured to check for dependencies, setup shortcuts write registry entries.
These are standard things in building real world desktop apps.

I take on board your point about OSX version and will look a version check.

**Comment by hferreira** [comment]
I understand your point of view.
Currently this AIR Desktop App that I'm talking about is available for macOS and Windows, using a propor installer for macOS and another one for Windows and I'm using shared runtime and 0 ANE's.

**Comment by hferreira** [comment]
I understand your point of view.
Currently this AIR Desktop App that I'm talking about is available for macOS and Windows, using a propor installer for macOS and another one for Windows and I'm using shared runtime and 0 ANE's.

**Comment by hferreira** [comment]
I understand your point of view.
Currently this AIR Desktop App that I'm talking about is available on macOS and Windows, using a installer for macOS and another one for Windows and I'm using shared runtime (included on the setup with Adobe authorization of course) and 0 ANE's (shared runtime don't support ANE's).
I'm considering moving to captive runtime (because in the future we will have AIR with support for Windows x64 and hopefully also supporting ANE's x64).
But unfortunately from my experience install of runtimes fails many times (specially on very old machines) so I'm considering a very basic setup with the App and 0 additional runtimes.
This will garantee 100% of good experience install my App.
The small percentage of people with Windows 10 and without Visual C++ 2015 distributable already installed by other Apps, can then install separately.

**Comment by tuarua** [comment]
ok.

**Comment by hferreira** [comment]
Thanks.
