### ISSUE TITLE
AIR for Windows 64 bits

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#6]
Hello,

With the new AIR for Windows 64 bits, your ANE don't need to be recompiled to support that ?

Regards,
Hugo.

**Comment by tuarua** [comment]
No. ANE's need to be recompiled as x64 to work with Air 64 bit.
At the moment this is not possible until Adobe resolve an issue in the SDK.

**Comment by hferreira** [comment]
So, I have 2 choices:
1. Use your ANE and accept com continue with 32 bits
2. Use AIR 64 bits and don't use any ANE

Until Adobe support ANEs compiled for x64.

**Comment by tuarua** [comment]
The Windows 64bit AIRSDK has been updated and now supports 64bit ANEs.  I confirmed with a quick test.
Will add to this ANE, perhaps to a separate branch.

**Comment by hferreira** [comment]
Very good news :)
I saw today the update but I didn't know that they support now ANE's.

**Comment by tuarua** [comment]
64 bit now added

**Comment by hferreira** [comment]
Very cool.
