### ISSUE TITLE
isSupported does not work

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#7]
Hello,

The propery isSupported is completly ignored.
You told before that the Windows 10 version will crah on macOS and also on previous versions of Windows.
However I saw the isSupported property and it's complety ignored.

**Comment by tuarua** [comment]
https://github.com/tuarua/DesktopToastANE/blob/master/native_extension/src/com/tuarua/DesktopToastANE.as#L66

isSupported returns true when the OS is either Win8 || Win10 || OSX
What do you mean it doesn't work ? What are you expecting it to do ?

You should use your own OS check to determine which namespace to use as per the example. Using the wrong namespace eg osx on Windows will cause a crash.

**Comment by hferreira** [comment]
OK, thanks.
