### ISSUE TITLE
I can't package targeting .air (for desktop)

### ISSUE THREAD

**Issue by leossmith** [tuarua/DesktopToastANE#8]
I am trying to package my project with your ANE as an .air for desktop, but i get the following error:

![air_ane](https://cloud.githubusercontent.com/assets/4300876/24265434/35517e28-100c-11e7-8c45-a5824c349717.PNG)

Is it possible to package it like this or do i have to do it as native installer or captive time? 

Thank you.

**Comment by tuarua** [comment]
You can't use ANEs with a .air package. It must be packaged as an exe.

Please see the Answer here.
http://stackoverflow.com/questions/18965488/flash-builder-fail-to-export-release-build

**Comment by leossmith** [comment]
Thank you for your quick reply.
